resolver: ghc-9.2.1
extra-deps:
  - aeson-2.0.2.0
  - assoc-1.0.2
  - attoparsec-0.14.3
  - base-compat-0.12.1
  - base-compat-batteries-0.12.1
  - base-orphans-0.8.6
  - bifunctors-5.5.11
  - binary-parser-0.5.7.1
  - bytestring-strict-builder-0.4.5.5
  - case-insensitive-1.2.1.0
  - cereal-0.5.8.2
  - charset-0.3.9
  - comonad-5.0.8
  - contravariant-1.5.5
  - cryptohash-md5-0.11.101.0
  - cryptohash-sha1-0.11.101.0
  - data-bword-0.1.0.1
  - data-checked-0.3
  - data-default-class-0.1.2.0
  - data-dword-0.3.2.1
  - data-endian-0.1.1
  - data-fix-0.3.2
  - data-serializer-0.3.5
  - data-textual-0.3.0.3
  - deferred-folds-0.9.18
  - distributive-0.6.2.1
  - dlist-1.0
  - entropy-0.4.1.7
  - foldl-1.4.12
  - hashable-1.4.0.1
  - hashtables-1.3
  - hasql-1.5.0.1
  - headed-megaparsec-0.2.0.2
  - indexed-traversable-0.1.2
  - indexed-traversable-instances-0.1.1
  - integer-logarithms-1.0.3.1
  - megaparsec-9.2.0
  - network-info-0.2.0.10
  - network-ip-0.3.0.3
  - OneTuple-0.3.1
  - parser-combinators-1.3.0
  - parsers-0.12.10
  - postgresql-binary-0.12.4.2
  - postgresql-libpq-0.9.4.3
  - postgresql-syntax-0.4
  - primitive-0.7.3.0
  - profunctors-5.6.2
  - random-1.2.1
  - scientific-0.3.7.0
  - selective-0.5
  - semialign-1.2.0.1
  - semigroupoids-5.3.6
  - semigroups-0.20
  - split-0.2.3.4
  - splitmix-0.1.0.4
  - StateVar-1.2.2
  - strict-0.4.0.1
  - tagged-0.8.6.1
  - template-haskell-compat-v0208-0.1.7
  - text-builder-0.6.6.3
  - text-latin1-0.3.1
  - text-printer-0.5.0.2
  - text-short-0.1.4
  - th-abstraction-0.4.3.0
  - these-1.1.1.1
  - time-compat-1.9.6.1
  - transformers-compat-0.7.1
  - type-hint-0.1
  - unordered-containers-0.2.16.0
  - uuid-1.3.15
  - uuid-types-1.0.5
  - vector-0.12.3.1
  - witherable-0.4.2
allow-newer: true
